version: '3.3'

services:
  #service 3: definition of your spring-boot app
  url-shortener-auth-service:                        #it is just a name, which will be used only in this file.
    image: url-shortener-auth-service               #name of the image after dockerfile executes
    container_name: url-shortener-auth-service-app  #name of the container created from docker image
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
      - "8080:8080"                       #docker container port with your os port
    restart: always

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db2:3306/customer?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mukit